name: pytest and flake8

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Berlin

    - name: Install dependencies
      run: |
        pip install flake8 pytest
        pip install pytest-github-actions-annotate-failures
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .[teamproject]

    - name: Install plugin
      run: pip install pytest-github-actions-annotate-failures
    
    - name: flake8
      uses: wearerequired/lint-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        flake8: true
        flake8_args: "--ignore W503"
    
    - name: pytest
      run: pytest
