name: coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Berlin

    - name: Install dependencies
      run: |
        pip3 install lxml
        pip install coveralls
        pip install pytest
        pip install coverage
        pip install pytest-github-actions-annotate-failures
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .[teamproject]
    
    - name: Coverage
      run: coverage run -m --omit=*/tests/*,*/bl_predictor/gui.py,*/bl_predictor/gui_slider_widget.py pytest
    
    - name: Upload coverage data to coveralls.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: coveralls --service=github
