name: Pytest all testclasses

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        python-version: 3.8
  
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Berlin

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install teamproject package
      run: pip install -e .[teamproject]

    - name: Install plugin
      run: pip install pytest-github-actions-annotate-failures

    - run: pytest
